//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp.DbModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_AccountRecord
    {
        public string FAccountRecordSn { get; set; }
        public string FTransId { get; set; }
        public string FBankId { get; set; }
        public string FInstitutionId { get; set; }
        public string FAccountNumber { get; set; }
        public int FTransType { get; set; }
        public System.DateTime FTransTime { get; set; }
        public string FPayerAccountName { get; set; }
        public string FPayerAccountNumber { get; set; }
        public decimal FAmount { get; set; }
        public string FNote { get; set; }
        public string FRemark { get; set; }
    }
}
