//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp.DbModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_AmountWhitelist
    {
        public string FWhitelistID { get; set; }
        public string FAccountWhitelistID { get; set; }
        public string FInterfaceReceiveID { get; set; }
        public string FInstitutionID { get; set; }
        public string FProjectCode { get; set; }
        public string FAccountNumber { get; set; }
        public string FBankId { get; set; }
        public int FBizStatus { get; set; }
        public decimal FAmount { get; set; }
        public string FRemark { get; set; }
        public string FResponseMsg { get; set; }
        public System.DateTime FCreateTime { get; set; }
        public int FStatus { get; set; }
    }
}
