//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp.DbModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_CPSinPay
    {
        public string FTradeSerialNumber { get; set; }
        public string FInterFaceSn { get; set; }
        public string FInstitution { get; set; }
        public string FBankId { get; set; }
        public string FProjectCode { get; set; }
        public string FCPPaymentNo { get; set; }
        public string FMerchantID { get; set; }
        public string FTradeDate { get; set; }
        public string FAccountNO { get; set; }
        public string FAccountName { get; set; }
        public string FCertType { get; set; }
        public string FCertID { get; set; }
        public string FBank { get; set; }
        public string FProvince { get; set; }
        public string FCity { get; set; }
        public decimal FAmount { get; set; }
        public string FPurpose { get; set; }
        public string FBranch { get; set; }
        public string FPayFlag { get; set; }
        public string FVersion { get; set; }
        public string FChannelType { get; set; }
        public string FPayMode { get; set; }
        public string FUserID { get; set; }
        public string FRegisterTime { get; set; }
        public string FEMail { get; set; }
        public string FMobilePhone { get; set; }
        public string FDiskSN { get; set; }
        public string FMACAddresses { get; set; }
        public string FIMEI { get; set; }
        public string FIP { get; set; }
        public string FCoordinates { get; set; }
        public string FBaseStationSN { get; set; }
        public string FCodeInputType { get; set; }
        public string FReserveMobile { get; set; }
        public string FDesc { get; set; }
        public int FStatus { get; set; }
        public string FResponseMsg { get; set; }
        public System.DateTime FCreateTime { get; set; }
    }
}
