//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp.DbModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_InterFaceReceive
    {
        public string FInterFaceSn { get; set; }
        public string FExecutor { get; set; }
        public string FBankId { get; set; }
        public string FInstitutionId { get; set; }
        public string FProjectCode { get; set; }
        public string FCode { get; set; }
        public string FPlaintTxt { get; set; }
        public string FData { get; set; }
        public string FToken { get; set; }
        public Nullable<System.DateTime> FRequestTime { get; set; }
        public Nullable<System.DateTime> FResponseTime { get; set; }
        public Nullable<int> FResponseStatus { get; set; }
        public string FResponseMsg { get; set; }
    }
}
