//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp.DbModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_NoticeRemitCMF
    {
        public string FBankId { get; set; }
        public string FInstitutionId { get; set; }
        public string FFromType { get; set; }
        public string FFromChannel { get; set; }
        public string FSource { get; set; }
        public string FNoticeRemitCMFSN { get; set; }
        public int FType { get; set; }
        public string FInterFaceSn { get; set; }
        public string FProjectCode { get; set; }
        public string FProjectName { get; set; }
        public string FCMFEAN { get; set; }
        public decimal FAmount { get; set; }
        public string FRemark { get; set; }
        public string FValueBeginTime { get; set; }
        public Nullable<int> Fstatus { get; set; }
        public string FIP { get; set; }
        public Nullable<System.DateTime> FTime { get; set; }
        public string FBizType { get; set; }
        public string FAccountProvince { get; set; }
        public string FAccountCity { get; set; }
        public string FAccountBranchBank { get; set; }
        public string FAccountName { get; set; }
        public string FAccountNumber { get; set; }
    }
}
