//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp.DbModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_PaymentByGateWayAccount
    {
        public string FBankId { get; set; }
        public string FPaymentNo { get; set; }
        public string FInstitutionId { get; set; }
        public string FAccountName { get; set; }
        public string FAccountNumber { get; set; }
        public string FAccountCity { get; set; }
        public string FAccountProvince { get; set; }
        public string FAccountBranchBank { get; set; }
        public Nullable<decimal> FAmount { get; set; }
        public Nullable<int> FStatus { get; set; }
        public System.DateTime FCreateTime { get; set; }
        public int FHasQuery { get; set; }
    }
}
