//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp.DbModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_PaymentByGatewaySign
    {
        public string FPaymentNo { get; set; }
        public string FInstitutionId { get; set; }
        public string FBankId { get; set; }
        public string FProjectCode { get; set; }
        public string FInterfaceSn { get; set; }
        public Nullable<decimal> FPayAmount { get; set; }
        public string FAccountBankId { get; set; }
        public Nullable<int> FAccountType { get; set; }
        public string FAccountNo { get; set; }
        public string FAccountSeq { get; set; }
        public string FNotificationURL { get; set; }
        public string FUsage { get; set; }
        public string FRemark { get; set; }
        public int FStatus { get; set; }
        public System.DateTime FCreateTime { get; set; }
        public string FAccountNumber { get; set; }
        public string FAccountName { get; set; }
    }
}
