//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp.DbModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Project
    {
        public string FProjectCode { get; set; }
        public string FInterFaceSn { get; set; }
        public string FBankId { get; set; }
        public string FInstitutionId { get; set; }
        public string FProjectName { get; set; }
        public int FProjectType { get; set; }
        public Nullable<decimal> FAmount { get; set; }
        public Nullable<decimal> FLeftAmount { get; set; }
        public Nullable<int> FPartsCount { get; set; }
        public Nullable<decimal> FInvestmentInterest { get; set; }
        public Nullable<System.DateTime> FValueBegin { get; set; }
        public Nullable<int> FDuration { get; set; }
        public Nullable<int> FBankAccountType { get; set; }
        public string FReceiveBankName { get; set; }
        public string FReceiveBankID { get; set; }
        public string FReceiveBankAccountName { get; set; }
        public string FReceiveBankAccountNo { get; set; }
        public string FReceiveBankProvince { get; set; }
        public string FReceiveBankCity { get; set; }
        public string FReceiveBankBranchName { get; set; }
        public string FReceiveBankUnionCode { get; set; }
        public Nullable<System.DateTime> FTime { get; set; }
    }
}
