//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp.DbModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_UnitedPayment
    {
        public string FPaymentNo { get; set; }
        public string FInstitutionId { get; set; }
        public string FBankId { get; set; }
        public string FInterFaceSn { get; set; }
        public string FProjectCode { get; set; }
        public decimal FAmount { get; set; }
        public string FRemark { get; set; }
        public string FAccountBankId { get; set; }
        public Nullable<int> FAccountType { get; set; }
        public string FAccountName { get; set; }
        public string FAccountNumber { get; set; }
        public string FBranchName { get; set; }
        public string FAccountBankUnionCode { get; set; }
        public string FProvince { get; set; }
        public string FCity { get; set; }
        public string FTxSNBinding { get; set; }
        public string FCardType { get; set; }
        public string FIdType { get; set; }
        public string FIdNo { get; set; }
        public string FCuryId { get; set; }
        public int FPaymentType { get; set; }
        public Nullable<int> FStatus { get; set; }
        public Nullable<int> FCfcaStatus { get; set; }
        public string FBizType { get; set; }
        public System.DateTime FCreateTime { get; set; }
        public string FInvestmentOrderNo { get; set; }
        public string FIdentificationType { get; set; }
        public string FIdentificationNumber { get; set; }
        public string FPhoneNumber { get; set; }
    }
}
