//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp.DbModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_PaymentByCMF
    {
        public string FPaymentNo { get; set; }
        public string FInstitutionId { get; set; }
        public string FInvestmentOrderNo { get; set; }
        public string FProjectCode { get; set; }
        public string FProjectName { get; set; }
        public string FBankId { get; set; }
        public string FInterFaceSn { get; set; }
        public string FUserID { get; set; }
        public string FFromType { get; set; }
        public string FFromChannel { get; set; }
        public string FSource { get; set; }
        public string FValueBegin { get; set; }
        public int FType { get; set; }
        public string FCMFEAN { get; set; }
        public string FCMFTEAN { get; set; }
        public string FIP { get; set; }
        public decimal FAmount { get; set; }
        public string FRemark { get; set; }
        public int FIsdeductebank { get; set; }
        public Nullable<int> FStatus { get; set; }
        public Nullable<System.DateTime> FCreateTime { get; set; }
        public string FBizType { get; set; }
    }
}
