// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace HelloWeb.MessageSystem.OpenSearch.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class DocumentResponse
    {
        /// <summary>
        /// Initializes a new instance of the DocumentResponse class.
        /// </summary>
        public DocumentResponse() { }

        /// <summary>
        /// Initializes a new instance of the DocumentResponse class.
        /// </summary>
        public DocumentResponse(string error = default(string), string json = default(string), bool? success = default(bool?))
        {
            Error = error;
            Json = json;
            Success = success;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "error")]
        public string Error { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "json")]
        public string Json { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "success")]
        public bool? Success { get; set; }

    }
}
