// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace HelloWeb.MessageSystem.OpenSearch.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class DocumentRequest
    {
        /// <summary>
        /// Initializes a new instance of the DocumentRequest class.
        /// </summary>
        public DocumentRequest() { }

        /// <summary>
        /// Initializes a new instance of the DocumentRequest class.
        /// </summary>
        public DocumentRequest(string appName = default(string), object fields = default(object), string tableName = default(string))
        {
            AppName = appName;
            Fields = fields;
            TableName = tableName;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "appName")]
        public string AppName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "fields")]
        public object Fields { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "tableName")]
        public string TableName { get; set; }

    }
}
