// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace HelloWeb.MessageSystem.OpenSearch.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class SuggestRequest
    {
        /// <summary>
        /// Initializes a new instance of the SuggestRequest class.
        /// </summary>
        public SuggestRequest() { }

        /// <summary>
        /// Initializes a new instance of the SuggestRequest class.
        /// </summary>
        public SuggestRequest(string appName = default(string), int? hits = default(int?), string query = default(string), int? start = default(int?), string suggestName = default(string))
        {
            AppName = appName;
            Hits = hits;
            Query = query;
            Start = start;
            SuggestName = suggestName;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "appName")]
        public string AppName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "hits")]
        public int? Hits { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "query")]
        public string Query { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "start")]
        public int? Start { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "suggestName")]
        public string SuggestName { get; set; }

    }
}
