// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace HelloWeb.MessageSystem.SDK.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;

    /// <summary>
    /// 日志信息
    /// </summary>
    public partial class LogModel
    {
        /// <summary>
        /// Initializes a new instance of the LogModel class.
        /// </summary>
        public LogModel() { }

        /// <summary>
        /// Initializes a new instance of the LogModel class.
        /// </summary>
        public LogModel(string projectName = default(string), string appName = default(string), string shortMessage = default(string), string fullMessage = default(string), int? logLevelId = default(int?), IDictionary<string, string> extended = default(IDictionary<string, string>), DateTime? createdOnUtc = default(DateTime?))
        {
            ProjectName = projectName;
            AppName = appName;
            ShortMessage = shortMessage;
            FullMessage = fullMessage;
            LogLevelId = logLevelId;
            Extended = extended;
            CreatedOnUtc = createdOnUtc;
        }

        /// <summary>
        /// 项目名称
        /// </summary>
        [JsonProperty(PropertyName = "ProjectName")]
        public string ProjectName { get; set; }

        /// <summary>
        /// 应用名称
        /// </summary>
        [JsonProperty(PropertyName = "AppName")]
        public string AppName { get; set; }

        /// <summary>
        /// 日志信息
        /// </summary>
        [JsonProperty(PropertyName = "ShortMessage")]
        public string ShortMessage { get; set; }

        /// <summary>
        /// 日志异常详细信息
        /// </summary>
        [JsonProperty(PropertyName = "FullMessage")]
        public string FullMessage { get; set; }

        /// <summary>
        /// 日志等级ID
        /// </summary>
        [JsonProperty(PropertyName = "LogLevelId")]
        public int? LogLevelId { get; set; }

        /// <summary>
        /// 扩展信息
        /// </summary>
        [JsonProperty(PropertyName = "Extended")]
        public IDictionary<string, string> Extended { get; set; }

        /// <summary>
        /// 创建时间UTC
        /// </summary>
        [JsonProperty(PropertyName = "CreatedOnUtc")]
        public DateTime? CreatedOnUtc { get; set; }

    }
}
