// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace HelloWeb.MessageSystem.SDK.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// 日志信息
    /// </summary>
    public partial class LogModel
    {
        /// <summary>
        /// Initializes a new instance of the LogModel class.
        /// </summary>
        public LogModel() { }

        /// <summary>
        /// Initializes a new instance of the LogModel class.
        /// </summary>
        public LogModel(string uniqueSequence = default(string), string projectName = default(string), string appName = default(string), string message = default(string), int? level = default(int?), object exception = default(object), DateTime? cTime = default(DateTime?))
        {
            UniqueSequence = uniqueSequence;
            ProjectName = projectName;
            AppName = appName;
            Message = message;
            Level = level;
            Exception = exception;
            CTime = cTime;
        }

        /// <summary>
        /// 跟踪流水
        /// </summary>
        [JsonProperty(PropertyName = "UniqueSequence")]
        public string UniqueSequence { get; set; }

        /// <summary>
        /// 项目名称
        /// </summary>
        [JsonProperty(PropertyName = "ProjectName")]
        public string ProjectName { get; set; }

        /// <summary>
        /// 应用名称
        /// </summary>
        [JsonProperty(PropertyName = "AppName")]
        public string AppName { get; set; }

        /// <summary>
        /// 日志信息
        /// </summary>
        [JsonProperty(PropertyName = "Message")]
        public string Message { get; set; }

        /// <summary>
        /// 日志等级
        /// </summary>
        [JsonProperty(PropertyName = "Level")]
        public int? Level { get; set; }

        /// <summary>
        /// 异常信息
        /// </summary>
        [JsonProperty(PropertyName = "Exception")]
        public object Exception { get; set; }

        /// <summary>
        /// 创建时间
        /// </summary>
        [JsonProperty(PropertyName = "CTime")]
        public DateTime? CTime { get; set; }

    }
}
