// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace HelloWeb.MessageSystem.SDK.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// 日志响应信息
    /// </summary>
    public partial class LogResponse
    {
        /// <summary>
        /// Initializes a new instance of the LogResponse class.
        /// </summary>
        public LogResponse() { }

        /// <summary>
        /// Initializes a new instance of the LogResponse class.
        /// </summary>
        public LogResponse(bool? success = default(bool?), string errorMessage = default(string), DateTime? responseTime = default(DateTime?))
        {
            Success = success;
            ErrorMessage = errorMessage;
            ResponseTime = responseTime;
        }

        /// <summary>
        /// 是否成功
        /// </summary>
        [JsonProperty(PropertyName = "Success")]
        public bool? Success { get; set; }

        /// <summary>
        /// 错误信息
        /// </summary>
        [JsonProperty(PropertyName = "ErrorMessage")]
        public string ErrorMessage { get; set; }

        /// <summary>
        /// 响应时间
        /// </summary>
        [JsonProperty(PropertyName = "ResponseTime")]
        public DateTime? ResponseTime { get; set; }

    }
}
