//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ATSEntities : DbContext
    {
        public ATSEntities()
            : base("name=ATSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<T_AccountBalance> T_AccountBalance { get; set; }
        public virtual DbSet<T_AccountRecord> T_AccountRecord { get; set; }
        public virtual DbSet<T_AccountRecordIn> T_AccountRecordIn { get; set; }
        public virtual DbSet<T_AmountWhitelist> T_AmountWhitelist { get; set; }
        public virtual DbSet<T_Asset> T_Asset { get; set; }
        public virtual DbSet<T_BatchSettlement> T_BatchSettlement { get; set; }
        public virtual DbSet<T_BatchSettlementVirtual> T_BatchSettlementVirtual { get; set; }
        public virtual DbSet<T_Binding> T_Binding { get; set; }
        public virtual DbSet<T_BindingHistory> T_BindingHistory { get; set; }
        public virtual DbSet<T_CfcaCallBack> T_CfcaCallBack { get; set; }
        public virtual DbSet<T_CPSinPay> T_CPSinPay { get; set; }
        public virtual DbSet<T_ErrLog> T_ErrLog { get; set; }
        public virtual DbSet<T_InstitutionSetting> T_InstitutionSetting { get; set; }
        public virtual DbSet<T_InterFaceReceive> T_InterFaceReceive { get; set; }
        public virtual DbSet<T_InterFaceSend> T_InterFaceSend { get; set; }
        public virtual DbSet<T_InvestmentOrder> T_InvestmentOrder { get; set; }
        public virtual DbSet<T_NoticeRemitCMF> T_NoticeRemitCMF { get; set; }
        public virtual DbSet<T_OperateRecord> T_OperateRecord { get; set; }
        public virtual DbSet<T_PayByDeduction> T_PayByDeduction { get; set; }
        public virtual DbSet<T_PayByDeductionHistory> T_PayByDeductionHistory { get; set; }
        public virtual DbSet<T_PayByDeductionUcs> T_PayByDeductionUcs { get; set; }
        public virtual DbSet<T_PayByDeductionUcsHistory> T_PayByDeductionUcsHistory { get; set; }
        public virtual DbSet<T_PaymentByCMF> T_PaymentByCMF { get; set; }
        public virtual DbSet<T_PaymentByCMFHistory> T_PaymentByCMFHistory { get; set; }
        public virtual DbSet<T_PaymentByDeduction> T_PaymentByDeduction { get; set; }
        public virtual DbSet<T_PaymentByDeductionHistory> T_PaymentByDeductionHistory { get; set; }
        public virtual DbSet<T_PaymentByGateway> T_PaymentByGateway { get; set; }
        public virtual DbSet<T_PaymentByGateWayAccount> T_PaymentByGateWayAccount { get; set; }
        public virtual DbSet<T_PaymentByGatewaySign> T_PaymentByGatewaySign { get; set; }
        public virtual DbSet<T_PaymentBySignDeduction> T_PaymentBySignDeduction { get; set; }
        public virtual DbSet<T_PaymentByStabilizationFund> T_PaymentByStabilizationFund { get; set; }
        public virtual DbSet<T_PaymentByStabilizationFundHistory> T_PaymentByStabilizationFundHistory { get; set; }
        public virtual DbSet<T_Project> T_Project { get; set; }
        public virtual DbSet<T_ProjectDeduction> T_ProjectDeduction { get; set; }
        public virtual DbSet<T_QuickPayment> T_QuickPayment { get; set; }
        public virtual DbSet<T_QuickPaymentHistory> T_QuickPaymentHistory { get; set; }
        public virtual DbSet<T_QuickRefund> T_QuickRefund { get; set; }
        public virtual DbSet<T_QuickRefundHistory> T_QuickRefundHistory { get; set; }
        public virtual DbSet<T_RefundByCMF> T_RefundByCMF { get; set; }
        public virtual DbSet<T_RefundByDeduction> T_RefundByDeduction { get; set; }
        public virtual DbSet<T_RefundByGateway> T_RefundByGateway { get; set; }
        public virtual DbSet<T_RefundBySignDeduction> T_RefundBySignDeduction { get; set; }
        public virtual DbSet<T_Repay> T_Repay { get; set; }
        public virtual DbSet<T_RepayCMF> T_RepayCMF { get; set; }
        public virtual DbSet<T_RepayHistory> T_RepayHistory { get; set; }
        public virtual DbSet<T_RepayOrderHistory> T_RepayOrderHistory { get; set; }
        public virtual DbSet<T_RepayTempCMF> T_RepayTempCMF { get; set; }
        public virtual DbSet<T_Role> T_Role { get; set; }
        public virtual DbSet<T_RoleAccess> T_RoleAccess { get; set; }
        public virtual DbSet<T_Settlement> T_Settlement { get; set; }
        public virtual DbSet<T_SettlementByStabilizationFund> T_SettlementByStabilizationFund { get; set; }
        public virtual DbSet<T_SettlementByStabilizationFundHistory> T_SettlementByStabilizationFundHistory { get; set; }
        public virtual DbSet<T_SettlementHistory> T_SettlementHistory { get; set; }
        public virtual DbSet<T_SettlementVirtual> T_SettlementVirtual { get; set; }
        public virtual DbSet<T_UnBinding> T_UnBinding { get; set; }
        public virtual DbSet<T_UnitedPayment> T_UnitedPayment { get; set; }
        public virtual DbSet<T_UnitedPaymentHistory> T_UnitedPaymentHistory { get; set; }
        public virtual DbSet<T_UnitedRefund> T_UnitedRefund { get; set; }
        public virtual DbSet<T_UnitedRepay> T_UnitedRepay { get; set; }
        public virtual DbSet<T_UnitedRepayHistory> T_UnitedRepayHistory { get; set; }
        public virtual DbSet<T_UserAuthority> T_UserAuthority { get; set; }
        public virtual DbSet<T_WhiteList> T_WhiteList { get; set; }
    }
}
