//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_BatchSettlement
    {
        public string FSettlementTaskSN { get; set; }
        public string FBatchNo { get; set; }
        public string FInstitutionID { get; set; }
        public string FProjectCode { get; set; }
        public int FTotalCount { get; set; }
        public decimal FTotalAmount { get; set; }
        public string FBatchRemark { get; set; }
        public int FStatus { get; set; }
        public System.DateTime FTime { get; set; }
    }
}
