//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_OperateRecord
    {
        public string FOperateRecordNo { get; set; }
        public string FBankId { get; set; }
        public string FInstitutionId { get; set; }
        public string FProjectCode { get; set; }
        public string FBusinessId { get; set; }
        public string FOperateType { get; set; }
        public string FOperateUser { get; set; }
        public System.DateTime FOperateTime { get; set; }
    }
}
