//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_PaymentByGateway
    {
        public string FPaymentNo { get; set; }
        public string FBankId { get; set; }
        public string FInstitutionId { get; set; }
        public string FInvestmentOrderNo { get; set; }
        public string FInterFaceSn { get; set; }
        public string FProjectCode { get; set; }
        public decimal FPayAmount { get; set; }
        public string FAccountName { get; set; }
        public string FAccountNumber { get; set; }
        public string FAccountBank { get; set; }
        public string FAccountBankID { get; set; }
        public string FAccountCertificationType { get; set; }
        public string FAccountCertificationNumber { get; set; }
        public int FStatus { get; set; }
        public string FAccountUserNo { get; set; }
        public string FAccountUserName { get; set; }
        public string FAccountSn { get; set; }
        public string FAccountProvinceCode { get; set; }
        public string FAccountProvince { get; set; }
        public string FAccountCityCode { get; set; }
        public string FAccountCity { get; set; }
        public string FAccountBranchBank { get; set; }
        public string FAccountBankUnionCode { get; set; }
        public string FAccountUserProperty { get; set; }
        public string FAccountCreateTime { get; set; }
        public string FAccountSign { get; set; }
        public int FAccountSignType { get; set; }
        public string FRemark { get; set; }
        public Nullable<System.DateTime> FCreateTime { get; set; }
        public string FBizType { get; set; }
    }
}
