//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_RepayCMF
    {
        public string FRepayCmfNo { get; set; }
        public string FUserId { get; set; }
        public string FBankId { get; set; }
        public string FInstitutionId { get; set; }
        public string FFromType { get; set; }
        public string FFromChannel { get; set; }
        public string FSource { get; set; }
        public string FInterFaceSn { get; set; }
        public int FType { get; set; }
        public string FIP { get; set; }
        public string FProjectCode { get; set; }
        public string FProjectName { get; set; }
        public string FPaymentNo { get; set; }
        public string FCmfEan { get; set; }
        public string FCmfTean { get; set; }
        public decimal FAmount { get; set; }
        public string FUsage { get; set; }
        public string FValueBeginTime { get; set; }
        public int FStatus { get; set; }
        public Nullable<System.DateTime> FTime { get; set; }
        public string FRemark { get; set; }
        public string FBizType { get; set; }
        public Nullable<int> FOrderType { get; set; }
    }
}
