//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_UnitedRefund
    {
        public string FRefundNo { get; set; }
        public string FInterFaceSn { get; set; }
        public string FOrderNo { get; set; }
        public string FInstitutionId { get; set; }
        public string FBankId { get; set; }
        public string FProjectCode { get; set; }
        public string FPaymentNo { get; set; }
        public decimal FAmount { get; set; }
        public Nullable<int> FSettlementType { get; set; }
        public string FAccountName { get; set; }
        public string FAccountNumber { get; set; }
        public string FAccountBankId { get; set; }
        public string FAccountBankName { get; set; }
        public string FProvince { get; set; }
        public string FCity { get; set; }
        public string FAccountBranchBank { get; set; }
        public string FRemark { get; set; }
        public string FAccountType { get; set; }
        public string FTxType { get; set; }
        public int FPaymentType { get; set; }
        public int FStatus { get; set; }
        public System.DateTime FCreateTime { get; set; }
    }
}
