//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_WhiteList
    {
        public string WhiteListNo { get; set; }
        public string FBankId { get; set; }
        public string FInstitutionId { get; set; }
        public string FProjectCode { get; set; }
        public string FAccountNumber { get; set; }
        public string FInterFaceSn { get; set; }
        public string FAccountName { get; set; }
        public int FAccountType { get; set; }
        public string FAccountBankUnionCode { get; set; }
        public string FAccountBankID { get; set; }
        public string FAccountBranchBank { get; set; }
        public string FAccountProvince { get; set; }
        public string FAccountCity { get; set; }
        public int FSettlementType { get; set; }
        public int FStatus { get; set; }
        public string FInvestNo { get; set; }
        public Nullable<decimal> FInvestLimit { get; set; }
        public Nullable<System.DateTime> FCreateTime { get; set; }
    }
}
